### ISSUE TITLE
Support for listening on Unix domain sockets

### ISSUE THREAD

**Issue by LINKIWI** [hay-kot/httpkit#3]
Hi, this library currently only allows listening on TCP sockets via `host` and `port` options.

I am interested in adding support to Homebox to listen on a local Unix domain socket. For example, listening on `/var/run/homebox/homebox.sock` which can be accessed as `curl --unix-socket /var/run/homebox/homebox.sock http://localhost`.

Please let me know if this is something that `httpkit` (and Homebox) is willing to support and maintain; if so, I will create and file a PR for it.

Approximately, I want to add the capability to start the HTTP server as:

```
// if a "socket" option is supplied instead of "host" and "port"

ln, err := net.Listen("unix", ...)
if err != nil { ... }

srv.Serve(ln)
```

**Comment by hay-kot** [comment]
I'm on the fence, why would someone want to use a unix socket over a normal http connection?

**Comment by LINKIWI** [comment]
The immediate motivation is a bit unique to our deployment conventions, but speaking more broadly, a couple reasons include:

* Supporting deployments where HTTP applications are fronted by an edge/ingress proxy. Applications themselves do not need to expose a TCP listener, since this responsibility (among others) is handled by the ingress tier. Also, while not particularly a concern for Homebox, UDS-based IPC is generally more performant than IPC over loopback TCP connections, and can also be done with zero-copy I/O in Linux.
* Leveraging filesystem ACLs for application server isolation in multitenant environments where network namespacing is not otherwise possible. For example, a `0600` Unix socket cannot be connected to by a process running as another non-root user, while any process on the same host would be able to connect to `localhost:7745` for example.

I understand that this is perhaps a unique use case, so also happy to maintain this functionality in our internal fork only.

**Comment by hay-kot** [comment]
Took some time to think through this. I think this highlights the problem with this package being so tightly coupled to HTTP servers. PR #7 takes the graceful shutdown process in implements into it's own Runner struct that accepts plugins. 

Once that PR is merged, I'll deprecate the server.Server struct and we can instead use the `graceful.Runner` to manage the startup/shutdown in a nice clean way and then you should be able to update HomeBox to utilize the unix socket and just swap the plugin implementation.

**Comment by hay-kot** [comment]
This will actually make testing in some of my other projects way more straight forward, so thanks for this issue!
